[tool.briefcase]
project_name = "Drift Commander"
bundle = "com.drift"
version = "0.1.0"
url = "https://github.com/your-username/drift-commander"
license = "BSD-3-Clause"
author = "Your Name"
author_email = "your-email@example.com"

[tool.briefcase.app.drifter]
formal_name = "Drift Commander"
description = "Tank Control Bluetooth App"
sources = ["src/drifter"]
requires = ["toga-android"]

[tool.briefcase.app.drifter.android]
permissions = [
    "android.permission.BLUETOOTH",
    "android.permission.BLUETOOTH_ADMIN",
    "android.permission.BLUETOOTH_SCAN",
    "android.permission.BLUETOOTH_CONNECT",
    "android.permission.ACCESS_FINE_LOCATION",
]
